# Generated by Django 2.2.4 on 2021-02-06 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '0001_initial'),
        ('service', '0001_initial'),
        ('client', '0001_initial'),
        ('staff', '0001_initial'),
        ('emergency_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=250)),
                ('event_description', models.TextField(blank=True)),
                ('event_remark', models.TextField(blank=True)),
                ('event_file', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(default='inactive', max_length=180, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_client_id', to='client.Cl')),
                ('emergency_service_id', models.ManyToManyField(blank=True, related_name='event_emergency_service_id', to='emergency_service.Cl')),
                ('service_id', models.ManyToManyField(blank=True, related_name='event_service_id', to='service.Cl')),
                ('sponsor_id', models.ManyToManyField(blank=True, related_name='event_sponsor_id', to='sponsor.Cl')),
                ('staff_id', models.ManyToManyField(blank=True, related_name='event_staff_id', to='staff.Cl')),
            ],
        ),
    ]
