# Generated by Django 2.2.4 on 2021-02-13 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photography_id', models.CharField(max_length=50)),
                ('photography_title', models.TextField(blank=True)),
                ('photography_txt', models.TextField(blank=True)),
                ('photography_icon', models.FileField(blank=True, upload_to='')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('status', models.CharField(default='inactive', max_length=180, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
            ],
        ),
    ]
