# Generated by Django 2.2.4 on 2021-02-14 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency_service', '0001_initial'),
        ('staff', '0001_initial'),
        ('sponsor', '0001_initial'),
        ('client', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package_id', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=250)),
                ('package_value', models.CharField(max_length=250)),
                ('people_preference', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('package_description', models.TextField(blank=True)),
                ('package_remark', models.TextField(blank=True)),
                ('package_file', models.FileField(blank=True, upload_to='')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('status', models.CharField(default='inactive', max_length=180, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_client_id', to='client.Cl')),
                ('emergency_service_id', models.ManyToManyField(blank=True, related_name='package_emergency_service_id', to='emergency_service.Cl')),
                ('service_id', models.ManyToManyField(blank=True, related_name='package_service_id', to='service.Cl')),
                ('sponsor_id', models.ManyToManyField(blank=True, related_name='package_sponsor_id', to='sponsor.Cl')),
                ('staff_id', models.ManyToManyField(blank=True, related_name='package_staff_id', to='staff.Cl')),
            ],
        ),
    ]
