# Generated by Django 2.2.4 on 2021-02-13 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picnic_id', models.CharField(max_length=50)),
                ('picnic_name', models.CharField(max_length=250)),
                ('picnic_place', models.CharField(max_length=250)),
                ('picnic_budget', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('picnic_description', models.TextField(blank=True)),
                ('status', models.CharField(default='inactive', max_length=180, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('staff_id', models.ManyToManyField(blank=True, related_name='picnic_staff_id', to='staff.Cl')),
            ],
        ),
    ]
